config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
    }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'profile/:id', to: 'users/registrations#edit_profile', as: 'edit_profile'                  #プロフィール変更ページ
    patch 'profile/:id', to: 'users/registrations#update_profile', as: 'update_profile'
    get 'phone/:id', to: 'users/registrations#edit_phone', as: 'edit_phone'                        #電話番号変更ページ
    patch 'phone/:id', to: 'users/registrations#update_phone', as: 'update_phone'
    get 'introduce/:id', to: 'users/registrations#edit_introduce', as: 'edit_introduce'            #本人情報変更ページ
    patch 'introduce/:id', to: 'users/registrations#update_introduce', as: 'update_introduce'

  end

  resources :users, only: [:show, :create, :new, :destroy,:update] do
    member do
      get 'card'          #クレカ追加ページ
      get 'address'       #住所変更ページ
      get 'like'          #いいね一覧ページ
      get 'now'           #出品中
      get 'buyed'         #売却済み
      get 'nowbuy'        #取引中
      get 'mybuy'         #購入した商品
      get 'mybuyed'       #過去に購入した商品
    end
    collection do
      get 'signout/:id'=> 'users#singout', as: 'signout'    #ログアウト確認ページ
      get 'deletion'
      get 'support'
    end
  end
  
  resources :cards, only: [:create, :show, :edit] do
    collection do
      post 'delete', to: 'cards#delete'     #クレカ削除アクション
      post 'show'                           #登録クレカ確認ページ
    end
    member do
      get 'confirmation'                    #クレカ追加ページ
    end
  end

  root 'items#index'
  resources :items do   
    resources :comments, only: [:create, :destroy, :show, :index] #itemコントローラのindexとshowにiコメントのidを渡す為、:show, :indexを追加した
    collection do
      get 'items/new/mid_category', to: 'items#mid_category'         #「子」カテゴリーテーブルを作成する為、記述した
      get 'items/new/small_category', to: 'items#small_category'     #「孫」カテゴリーテーブルを作成する為、記述した
      get 'purchase/:id'=> 'items#purchase', as: 'purchase'          #購入確認ページ
      post 'pay/:id'=> 'items#pay', as: 'pay'                        #httpメソッドはpostなので注意
      get 'done/:id'=> 'items#done', as: 'done'                      #購入完了ページ
      delete 'items/:id' => 'items#destroy'
      get :search                                                  #検索ページ
      #下記はいいね機能を付与する為のルーティング
      post   '/like/:item_id' => 'likes#like',   as: 'like'  #どのitemに対するlikeか判断する為、URI Patternは/like/:item_idのように記述した。
      delete '/like/:item_id' => 'likes#unlike', as: 'unlike'  #オプションでas:を記述することでPrefixの名前を指定出来る。
    end
  end  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  
  
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :birth_year
    belongs_to_active_hash :birth_moom
    belongs_to_active_hash :birth_day     
  
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy
  has_one :card 
  # いいね機能のアソシエーション
  has_many :likes, dependent: :destroy
  has_many :like_items, through: :likes, source: :item


  # バリデーション 
  validates :password,length: { minimum: 7}
  validates :nickname, presence: true  #空でないこと
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true, format: {with:/\A[ァ-ヶー－]+\z/}
  validates :last_name_kana, presence: true, format: {with:/\A[ァ-ヶー－]+\z/}
  validates :birthday_year_id, presence: true
  validates :birthday_moon_id, presence: true
  validates :birthday_day_id, presence: true


  def birthday
    "#{BirthYear.find(self.birthday_year_id).year}/#{BirthMoom.find(self.birthday_moom_id).month}/#{BirthDay.find(self.birthday_day_id).day}"
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?  #userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }  #User.form_omniauth、メゾットでuserとsnsをハッシュで返す
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]
      #APIから受け取ったレスポンスがrequest.env["omniauth.auth"]という変数に入っている
      #DB操作を行うメソッドUser.from_omniauthを仮で作り、上記変数を渡す
      #Userモデルのインスタンスを返させて＠userへ代入することで、その後の処理でdeviseのヘルパーを利用することができる
      

    if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
   
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]


  def new
    @user = User.new
  end
 
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    session["devise.regist_data"][:user]["password_confirmation"] = params[:user][:password_confirmation]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    if @user.save
      session["devise.regist_data"]["user"].clear
      sign_in(:user, @user)
    else
      render :new
    end
  end


  def edit_profile
    @profile = User.find(params[:id])
  end

  def update_profile
    @profile = User.find(params[:id])
    if @profile.update(account_update_params)
      sign_in(:user, @profile)
      redirect_to user_path(current_user.id)
    else
      flash.now[:alert] = @profile.errors.full_messages
      render :edit_profile
    end
  end

  def edit_phone
    @phone = User.find(params[:id])
  end

  def update_phone
    @phone = User.find(params[:id])
    if @phone.update(account_update_params)
      sign_in(:user, @phone)
      redirect_to user_path(current_user.id)
    else
      flash.now[:alert] = @phone.errors.full_messages
      render :edit_phone
    end
  end
  
  def edit_introduce
    @introduce = User.find(params[:id])
  end

  def update_introduce
    @introduce = User.find(params[:id])
    if @introduce.update(account_update_params)
      sign_in(:user, @introduce)
      redirect_to user_path(current_user.id)
    else
      flash.now[:alert] = @introduce.errors.full_messages
      render :edit_introduce
    end
  end

  def destroy
    if @user.destroy
      redirect_to deletion_users_path
    else
      flash[:notice] = 'アカウント削除できませんでした'
      redirect_to signout_users_path(current_user.id)
    end
  end

# < 編集後 ユーザーページへ >
  def after_update_path_for(resource)
    user_path(resource)
  end


protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :first_name,:last_name,:first_name_kana,:last_name_kana,:phone_number, :birthday_year_id, :birthday_moon_id, :birthday_day_id, :self_introduce ])
  end


  def address_params
    params.require(:address).permit(:postal_code, :prefecture_code, :city_name, :street, :street2)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(use_params)
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
  end

  def card
  end

  def address
    @address = Address.find(params[:id])
  end

  def update
    params[:user] == nil
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to user_path(current_user.id)
    else
      flash.now[:alert] = @address.errors.full_messages
      render :address
    end
  end


  def deletion
  end

  def like
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id).page(params[:page]).per(10)
  end

  def now
    @user = User.find_by(id: params[:id])
    @item = Item.where(user_id: @user.id).page(params[:page]).per(10)
  end

  def buyed
    @user = User.find_by(id: params[:id])
    @item = Item.where(user_id: @user.id).page(params[:page]).per(10)
  end

  def nowbuy
    @user = User.find_by(id: params[:id])
    @item = Item.where(user_id: @user.id).page(params[:page]).per(10)
  end

  def mybuy
    @user = User.find_by(id: params[:id])
    @item = Item.where(buyer_id: @user.id).page(params[:page]).per(10)
  end

  def mybuyed
    @user = User.find_by(id: params[:id])
    @item = Item.where(buyer_id: @user.id).page(params[:page]).per(10)
  end

  def support
  end

  private 
  def user_params 
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :first_name, :last_name,:first_name_kana, :last_name_kana, :introduction, :birthday_year_id, :birthday_moon_id, :birthday_day_id, :phone_number)
  end

  def address_params
    params.require(:address).permit(:postal_code, :prefecture_code, :city_name, :street)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_log-out.html.haml
.mypage__sub__content
  %form.mypage__sub__content-form
    %button.mypage__sub__content-form-btn 
      = link_to "ログアウト",destroy_user_session_path, method: :delete, class:"btn"
    %button.mypage__sub__content-form-btn
      = link_to "アカウント削除", user_registration_path, method: :delete, class: "btn"

app/views/users/_main-contents.html.haml
.mypage-content
  %a.user_box
    %figure
      -# - if @user.user_image?
        = image_tag @user.user_image.url 
      - else 
        = image_tag 'member_photo_noimage_thumb.png'
      %h2.user_box__name
        = @user.nickname
    .user_box__info
      %h2.user_box__info__evalution
        評価
        %span#count
        2
      %h2.user_box__info__transactions
        出品
        %span#count
        2
  .tabs
    %input#all{checked: 'checked', name: 'tab_item', type: 'radio'}/
    %label.tab_item{for: 'all'} お知らせ
    %input#doing{name: 'tab_item', type: 'radio'}/
    %label.tab_item{for: "doing"} やることリスト
    %ul#all_content.tab_content
      %li
        %a.mypage-item__list-link{href: "#"}
          %figure
            = image_tag 'hako1.png'
          .mypage-item__body
            .mypage-item__text 事務局からのメッセージ
          %time
            %i.icon-time
            %span 6時間前
      %li.mypage-content__item-index
        %a{href: "#"} 一覧を見る
    %ul#doing_content.tab_content
      %li
        %a.mypage-item__list-link{href: "#"}
          %figure
            = image_tag 'hako1.png'
          .mypage-item__body
            .mypage-item__text 現在やることはありません
            %time
              %i.icon-time
              %span 15時間前
      %li.mypage-content__item-index
        %a{href: "#"} 一覧を見る

app/views/users/_side-bar.html.haml
.mypage-side-bar
  %ul.mypage-side-bar__list
    %li
    = link_to user_path(current_user.id), class: 'mypage-side-bar__list-contents mypage-side-bar' do
      マイページ
      = icon 'fas', 'chevron-right'
    %li
    = link_to "#", class: 'mypage-side-bar__list-contents mypage-side-bar' do
      お知らせ
      = icon 'fas', 'chevron-right'
    %li
    = link_to "#", class: 'mypage-side-bar__list-contents mypage-side-bar' do
      やることリスト 
      = icon 'fas', 'chevron-right'
    %li
    = link_to like_user_path(current_user.id), class: 'mypage-side-bar__list-contents mypage-side-bar' do
      いいね！一覧
      = icon 'fas', 'chevron-right'
    %li
    = link_to new_item_path, class: 'mypage-side-bar__list-contents mypage-side-bar' do
      出品する
      = icon 'fas', 'chevron-right'
    %li
    = link_to "#", class: 'mypage-side-bar__list-contents mypage-side-bar' do
      下書き一覧
      = icon 'fas', 'chevron-right'
    %li
    = link_to now_user_path(current_user.id), class: 'mypage-side-bar__list-contents mypage-side-bar' do
      出品した商品 -出品中
      = icon 'fas', 'chevron-right'
    %li
    = link_to nowbuy_user_path(current_user.id), class: 'mypage-side-bar__list-contents mypage-side-bar' do
      出品した商品 -取引中
      = icon 'fas', 'chevron-right'
    %li
    = link_to buyed_user_path(current_user.id), class: 'mypage-side-bar__list-contents mypage-side-bar' do
      出品した商品 -売却済み
      = icon 'fas', 'chevron-right'
    %li
    = link_to mybuy_user_path(current_user.id), class: 'mypage-side-bar__list-contents mypage-side-bar' do
      購入した商品 -取引中
      = icon 'fas', 'chevron-right'
    %li
    = link_to mybuyed_user_path(current_user.id), class: 'mypage-side-bar__list-contents mypage-side-bar' do
      購入した商品 -過去の取引
      = icon 'fas', 'chevron-right'
    %li
    = link_to "#", class: 'mypage-side-bar__list-contents mypage-side-bar' do
      ニュース一覧
      = icon 'fas', 'chevron-right'
    %li
    = link_to "#", class: 'mypage-side-bar__list-contents mypage-side-bar' do
      評価一覧
      = icon 'fas', 'chevron-right'
    %li
    = link_to "#", class: 'mypage-side-bar__list-contents mypage-side-bar' do
      ガイド
      = icon 'fas', 'chevron-right'
    %li
    = link_to support_users_path, class: 'mypage-side-bar__list-contents mypage-side-bar' do
      お問い合わせ
      = icon 'fas', 'chevron-right'
    %h3
      よしペイ
  %ul.mypage-side-bar__list
    %li
    = link_to "#", class: 'mypage-side-bar__list-contents mypage-side-bar' do
      残高照会
      = icon 'fas', 'chevron-right'
  %h3.mypage-side-bar__nav-head
    設定
  %ul.mypage-side-bar__list
    %li
      = link_to edit_profile_path(current_user.id), class: 'mypage-side-bar__list-contents' do
        プロフィール
        = icon 'fas', 'chevron-right'
    %li
      = link_to address_user_path(current_user.id), class: 'mypage-side-bar__list-contents' do
        発送元・お届け先住所変更
        = icon 'fas', 'chevron-right'
    %li
      = link_to confirmation_card_path(current_user.id), class: 'mypage-side-bar__list-contents' do
        支払い方法
        = icon 'fas', 'chevron-right'
    %li
      = link_to edit_user_registration_path, class: 'mypage-side-bar__list-contents' do
        メール/パスワード
        = icon 'fas', 'chevron-right'
    %li
      = link_to edit_introduce_path(current_user.id), class: 'mypage-side-bar__list-contents' do
        本人情報
        = icon 'fas', 'chevron-right'
    %li
      = link_to edit_phone_path(current_user.id), class: 'mypage-side-bar__list-contents' do
        電話番号の確認
        = icon 'fas', 'chevron-right'
    %li
      = link_to signout_users_path(current_user.id), method: :get, class: 'mypage-side-bar__list-contents' do
        ログアウト
        = icon 'fas', 'chevron-right'

app/views/users/buyed.html.haml
= render "items/main-header"
.header-under
  .box-under
    .gretel-link
      - breadcrumb :buyed
      = breadcrumbs separator:  "&rsaquo;",class: "crumb-btn"
.wrraper
  .mypage
    = render 'users/side-bar'
    .main-products
      .title-group
        .gray-now-title
          = link_to "出品中", now_user_path(current_user.id), class: "now-field" 
        .white-trans-title
          = link_to "取引中", nowbuy_user_path(current_user.id), class: "trans-field" 
        .gray-buy-end
          = link_to "売却済み", buyed_user_path(current_user.id), class: "buy-end-field" 
      .products-group
        - @item.last(10).each do |item|
          - if item.buyer_id
            .groups
              .image
                = link_to done_items_path(item.id), class: "my-link" do
                  = image_tag item.images[0].image.url
              -if item.buyer_id.present? 
                .sold-like
                  .sold-inner
                    SOLD
              .info
                .title-field
                  = item.name.truncate(29)
                .other-field
                  %i.fas.fa-heart.heart
                  -# .count
                  -#   - if product.likes_count.present?
                  -#     = product.likes_count
                  -#   - else
                  -#     = "#{product.likes_count} 0"
                  .now-now-red
                    .now-text
                      売却済み
              .icon-field
                = link_to done_items_path(item.id) do
                  %i.fa.fa-angle-right.right-icon
      -# .page
      -#   = paginate(@product)
= render 'items/footer'

app/views/users/card.html.haml
= render "items/header"
.header-under
  .box-under
    .gretel-link
      - breadcrumb :card
      = breadcrumbs separator:  "&rsaquo;",class: "crumb-btn"

.wrraper
  .mypage
    = render 'users/side-bar'
    .card__box
      .card__box__head
        %h2 支払い方法
      .card__content
        .card__content__textbox
          %h3.card__content__textbox__text クレジットカード一覧
        .set__card
          .submit_button
            = link_to  new_user_card_path(current_user.id),class: "btn-red" do
              %i.far.fa-credit-card
                クレジットカードを追加する
        .set__regist
          %a{:href => '#'}
            %span 支払い方法について
            %i.fas.fa-chevron-right
= render 'items/footer'

app/views/users/like.html.haml
= render 'items/main-header'
.wrraper
  .mypage
    = render 'users/side-bar'
    .like-content
      %h2 いいね！一覧
      %ul 
        - @likes.last(10).each do |like|
          - item = like.item
          %li
            = link_to item_path(item.id), class: "mypage-item-link" do
              = image_tag item.images[0].src.url
              .mypage-item-body
                .mypage-item-name
                  = item.name
                .mypage-item-price
                  = "¥#{item.price}"
                %i.fas.fa-chevron-right
            -if item.buyer_id.present? 
              .item-sold-like
                .item-sold-like__inner
                  SOLD
        = paginate(@likes)
= render 'items/main-footer'

app/views/users/mybuy.html.haml
= render "items/main-header"
.header-under
  .box-under
    .gretel-link
      - breadcrumb :mybuy
      = breadcrumbs separator:  "&rsaquo;",class: "crumb-btn"
.wrraper
  .mypage
    = render 'users/side-bar'
    .main-products
      .title-group
        .mybuy-title
          取引中
      .products-group
        -# - @item.last(10).each do |item|
        -#   - if item.buyer_id
        -#     .groups
        -#       .image
        -#         = link_to done_items_path(item.id), class: "my-link" do
        -#           = image_tag item.images[0].image.url
        -#       -if item.buyer_id.present? 
        -#         .sold-like
        -#           .sold-inner
        -#             SOLD
              .info
                .title-field
                  = item.name.truncate(29)
                .other-field
                  %i.fas.fa-heart.heart
                  -# .count
                  -#   - if item.likes_count.present?
                  -#     = item.likes_count
                  -#   - else
                  -#     = "#{item.likes_count} 0"
                  .now-now-red
                    .now-text
                      売却済み
              .icon-field
                = link_to done_items_path(item.id) do
                  %i.fa.fa-angle-right.right-icon
      .page
        = paginate(@item)
= render 'items/footer'

app/views/users/mybuyed.html.haml
= render "items/main-header"
.header-under
  .box-under
    .gretel-link
      - breadcrumb :mybuy
      = breadcrumbs separator:  "&rsaquo;",class: "crumb-btn"
.wrraper
  .mypage
    = render 'users/side-bar'
    .main-products
      .title-group
        .mybuy-title
          過去の取引
      -# .products-group
      -#   - @.last(10).each do |item|
      -#     - if item.buyer_id
      -#       .groups
      -#         .image
      -#           = link_to item_path(item.id), class: "my-link" do
      -#             = image_tag item.images[0].image.url
      -#         -if item.buyer_id.present? 
      -#           .sold-like
      -#             .sold-inner
                    -# SOLD
              .info
                .title-field
                  = item.name.truncate(29)
                .other-field
                  %i.fas.fa-heart.heart
                  -# .count
                  -#   - if item.likes_count.present?
                  -#     = item.likes_count
                  -#   - else
                  -#     = "#{item.likes_count} 0"
                  .now-now-red
                    .now-text
                      売却済み
              .icon-field
                = link_to item_path(item.id) do
                  %i.fa.fa-angle-right.right-icon
      .page
        = paginate(@item)
= render 'items/footer'

app/views/users/now.html.haml
= render "items/main-header"
.header-under
  .box-under
    .gretel-link
      - breadcrumb :now
      = breadcrumbs separator:  "&rsaquo;",class: "crumb-btn"
.wrraper
  .mypage
    = render 'users/side-bar'
    .main-products
      .title-group
        .now-title
          = link_to "出品中", now_user_path(current_user.id), class: "now-field" ,id: "now-a"
        .trans-title
          = link_to "取引中", nowbuy_user_path(current_user.id), class: "trans-field" ,id: "now-b"
        .buy-end
          = link_to "売却済み",buyed_user_path(current_user.id), class: "buy-end-field" ,id: "now-c"
      .products-group
        - @item.last(10).each do |item|
          - unless item.buyer_id
            .groups
              .image
                = link_to items_path(item.id), class: "my-link" do
                  -# = image_tag item.images[0].image.url
              .info
                .title-field
                  = item.name.truncate(29)
                  .now-now
                    .now-text
                      出品中
              .icon-field
                = link_to item_path(item.id) do
                  %i.fa.fa-angle-right.right-icon
      .page
        = paginate(@item)
= render 'items/footer'

app/views/users/nowbuy.html.haml
= render "items/main-header"
.header-under
  .box-under
    .gretel-link
      - breadcrumb :nowbuy
      = breadcrumbs separator:  "&rsaquo;",class: "crumb-btn"
.wrraper
  .mypage
    = render 'users/side-bar'
    .main-products
      .title-group
        .gray-now-title
          = link_to "出品中", now_user_path(current_user.id), class: "now-field" 
        .white-trans-title
          = link_to "取引中", nowbuy_user_path(current_user.id), class: "trans-field" 
        .gray-buy-end
          = link_to "売却済み", buyed_user_path(current_user.id), class: "buy-end-field" 
      .products-group
        - @item.last(10).each do |item|
          - if item.buyer_id
            .groups
              .image
                = link_to done_items_path(item.id), class: "my-link" do
                  = image_tag item.images[0].image.url
              -if item.buyer_id.present? 
                .sold-like
                  .sold-inner
                    SOLD
              .info
                .title-field
                  = item.name.truncate(29)
                -# .other-field
                -#   %i.fas.fa-heart.heart
                -#   .count
                -#     - if product.likes_count.present?
                -#       = product.likes_count
                -#     - else
                -#       = "#{product.likes_count} 0"
                -#   .now-now-red
                -#     .now-text
                -#       売却済み
              .icon-field
                = link_to done_products_path(product.id) do
                  %i.fa.fa-angle-right.right-icon
      .page
        = paginate(@item)
= render 'items/footer'

app/views/users/show.html.haml
= render "items/main-header"
.header-under
  .box-under
    .gretel-link
      - breadcrumb :mypage
      = breadcrumbs separator:  "&rsaquo;",class: "crumb-btn"

.wrraper
  .mypage
    = render 'users/side-bar'
    = render 'users/main-contents'
= render 'items/main-footer'

app/views/users/singout.html.haml
= render "items/main-header"
.header-under
  .box-under
    .gretel-link
      - breadcrumb :sign
      = breadcrumbs separator:  "&rsaquo;",class: "crumb-btn"
.wrraper
  .mypage
    = render "side-bar"
    = render "log-out"
= render 'items/main-footer'