config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
    }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'profile/:id', to: 'users/registrations#edit_profile', as: 'edit_profile'                  #プロフィール変更ページ
    patch 'profile/:id', to: 'users/registrations#update_profile', as: 'update_profile'
    get 'phone/:id', to: 'users/registrations#edit_phone', as: 'edit_phone'                        #電話番号変更ページ
    patch 'phone/:id', to: 'users/registrations#update_phone', as: 'update_phone'
    get 'introduce/:id', to: 'users/registrations#edit_introduce', as: 'edit_introduce'            #本人情報変更ページ
    patch 'introduce/:id', to: 'users/registrations#update_introduce', as: 'update_introduce'

  end

  resources :users, only: [:show, :create, :new, :destroy,:update] do
    member do
      get 'card'          #クレカ追加ページ
      get 'address'       #住所変更ページ
      get 'like'          #いいね一覧ページ
      get 'now'           #出品中
      get 'buyed'         #売却済み
      get 'nowbuy'        #取引中
      get 'mybuy'         #購入した商品
      get 'mybuyed'       #過去に購入した商品
    end
    collection do
      get 'signout/:id'=> 'users#singout', as: 'signout'    #ログアウト確認ページ
      get 'deletion'
      get 'support'
    end
  end
  
  resources :cards, only: [:create, :show, :edit] do
    collection do
      post 'delete', to: 'cards#delete'     #クレカ削除アクション
      post 'show'                           #登録クレカ確認ページ
    end
    member do
      get 'confirmation'                    #クレカ追加ページ
    end
  end

  root 'items#index'
  resources :items do   
    resources :comments, only: [:create, :destroy, :show, :index] #itemコントローラのindexとshowにiコメントのidを渡す為、:show, :indexを追加した
    collection do
      get 'items/new/mid_category', to: 'items#mid_category'         #「子」カテゴリーテーブルを作成する為、記述した
      get 'items/new/small_category', to: 'items#small_category'     #「孫」カテゴリーテーブルを作成する為、記述した
      get 'purchase/:id'=> 'items#purchase', as: 'purchase'          #購入確認ページ
      post 'pay/:id'=> 'items#pay', as: 'pay'                        #httpメソッドはpostなので注意
      get 'done/:id'=> 'items#done', as: 'done'                      #購入完了ページ
      delete 'items/:id' => 'items#destroy'
      get :search                                                  #検索ページ
      #下記はいいね機能を付与する為のルーティング
      post   '/like/:item_id' => 'likes#like',   as: 'like'  #どのitemに対するlikeか判断する為、URI Patternは/like/:item_idのように記述した。
      delete '/like/:item_id' => 'likes#unlike', as: 'unlike'  #オプションでas:を記述することでPrefixの名前を指定出来る。
    end
  end  
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # gem 'active_hash'を導入したら、extend ActiveHash::Associations::ActiveRecordExtensionsとbelongs_to_active_hash :〇〇(モデル名)を記述する
  belongs_to :user

  has_many :category
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :likes, dependent: :destroy
  # 下記２行ははいいね機能のアソシエーション
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  accepts_nested_attributes_for :images, allow_destroy: true
  # allow_destroy: true ： 親のレコードが削除された際、関連付いている子のレコードも一緒に削除してくれます。(公式ドキュメント有ります)
  # accepts_nested_attributes_forは、paramsの○○s_attritbutes:というキーの中で特定の値を送ることで、親モデルに紐づいた子モデルの削除、更新が出来る。
  # この特定の値が送れるよう、JavaScriptの実装を行います。

  belongs_to_active_hash :condition, resence: true 
  belongs_to_active_hash :size, presence: true
  belongs_to_active_hash :delivery_date, presence: true
  belongs_to_active_hash :delivery_fee, presence: true
  belongs_to_active_hash :prefecture, presence: true
  belongs_to_active_hash :delivery_way, presence: true
  # belongs_to_active_hashメソッドを記述する事で、各モデル(〇〇.rb)とアソシエーションを定義出来る。

  validates :images,
  :condition,
  :category_id,
  :size,
  :delivery_fee,
  :delivery_way,
  :prefecture,
  :delivery_date,
  presence: true
  validates :name, presence: true, length: {maximum: 40} #商品名を40文字以上打てない様に設置した。
  validates :content,presence: true, length: {maximum: 1000} #商品説明が1000文字しか打てない様に設定した
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 300} #300円以下の金額は入力出来ない様に設定した
  

  def self.search(search)
    if search
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
  # scope :name, -> (search){ where('name LIKE(?)', "%#{search}%")}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_product, only: [:edit, :show, :update, :destroy, :purchase, :pay, :done]
  before_action :set_card, only: [:purchase, :pay, :done]


  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @item.images.build
    #.images.buildで@itemに画像のデータを追加で格納している
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      render :create
      # 出品画面で必須項目に全ての値が入力された際、保存がされてcreate画面に移動する
    else
      @image = @item.images.build
      render :new
      # else以下の記述の意味
      # 入力必須コマンドに値が格納されていない状態で出品してしまった場合、再度出品画面に遷移した際、画像の選択画面が消え画像挿入できなくなる。（必須 image = @item.images.build）
    end
  end

  def destroy
    if @item.destroy
      render :destory
    else
      redirect_to item_path(@item.id)
    end
  end
    
  def edit
    @parents = Category.order("id ASC").limit(607)
    # カテゴリーに保存されているデータを出力する為、記述した。
  end

  def update
    @parents = Category.all.order("id ASC").limit(607)
    # カテゴリーに保存されているデータを出力する為、記述した。
    if params[:item][:images_attributes] && @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      flash[:alert] = '商品情報を正しく入力してください'
     redirect_to edit_item_path
    end
  end

  def show
    @parents = Category.order("id ASC").limit(607)
    # カテゴリーに保存されているデータを出力する為、記述した。
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def mid_category
    @mid_categories = Category.where(ancestry: params[:big_category_id])
    render json: @mid_categories
  end

  def small_category
    @small_categories = Category.where(ancestry: "#{params[:big_category_id]}/#{params[:mid_category_id]}")
    render json: @small_categories
  end

  #< 商品購入アクション purchase、pay、done>
  def purchase
    if @card.blank?
      flash.now[:alert] = 'カードを登録してください。'
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    charge = Payjp::Charge.create(
    amount: @item.price,
    customer: @card.customer_id,
    card: params['payjp-token'],
    currency: 'jpy'
    )
    if @item.update( buyer_id: current_user.id)
      redirect_to done_items_path(@item.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def done
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    #保管した顧客IDでpayjpから情報取得
    customer = Payjp::Customer.retrieve(@card.customer_id)
    #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
    @default_card_information = customer.cards.retrieve(@card.card_id)
  end


  def search
    # @search_item = Item.ransack(params[:q])
    # @items = @search_item.result.page(params[:page])

    @item = Item.search(params[:keyword])
    @parents = Category.all.order("id ASC").limit(13)
    @q = Item.ransack(params[:q])
    if params[:buyer] == "2"
      @items = @q.result(distinct: true).where(buyer_id: nil)
    elsif params[:buyer] == "1"
      @items = @q.result(distinct: true).where.not(buyer_id: nil)
    else
      @items = Item.all
    end

    if params[:q].present?
      # 検索フォームからアクセスした時の処理
      @search = Item.ransack(search_params)
      @items = @search.result
    else
      # 検索フォーム以外からアクセスした時の処理
      params[:q] = { sorts: 'id desc' }
      @search = Item.ransack()
      @items = Item.all
    end
  end
      # @items = Item.search(params[:keyword])

  private
  def item_params
    params.require(:item).permit(:name, :content, :category_id, :size_id, :brand, :condition_id, :delivery_fee_id, :delivery_way_id,  :prefecture_id, :delivery_date_id, :price, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
    # images_attributes: [:src, :_destroy, :id]の意味を下記に記載
    # fields_forを利用して作成されたフォームから来る値は、○○s_attributes: [:××]という形でparamsに入る。これにより、itemとimageを紐つけしている。
    # ○○は関連付く側のモデルの名前(今回はimage)、××にはフォーム(今回は画像のカラム名は、src)に対応するカラムの名前が入る。
  end  

  def set_product
    @item = Item.find(params[:id])
    # :edit, :update, :showにitem.idを与える必要がある為、記述した
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def search_params
    params.require(:q).permit(:sorts)
    # 他のパラメーターもここに入れる
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error_message.html.haml
-if @item.errors.any? 
  .alert
    %ul
      -@item.errors.full_messages.each do |message| 
        %li= message

app/views/items/_footer.html.haml
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        = link_to "プライバシーポリシー", "#"
      %li
        = link_to "フリマ利用規約", "#"
      %li
        = link_to "特定商取引に関する表記", "#"
  = link_to root_path, class: "single-footer-logo" do
    = image_tag asset_path("logo.png"), alt: "FURIMA", width: "100", height: "36"
  %p
    %small © 2020 FURIMA

app/views/items/_header.html.haml
%header.single-header
  %h1
    = link_to root_path do
      = image_tag asset_path("logo.png"), alt: "FURIMA"

app/views/items/_main-footer.html.haml
%aside.appBanner
  .inner
    %h2 だれでもかんたん、人生を変えるフリマアプリ
    %p 今すぐ無料ダウンロード！
    .inner__icon
      = link_to root_path do
        = image_tag asset_path("download-on-the-app-store-apple.svg"),class: "abtn", alt: "download-on-the-app-store-apple.svg"
      = link_to root_path do
        = image_tag asset_path("google-play-download-android-app.svg"),class: "gbtn", alt: "google-play-download-android-app.svg"
.footer
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社）",root_path, class:"btn"
        %li
          = link_to "プライバシーポリシー",root_path, class:"btn"
        %li
          = link_to "FURIMA利用規約",root_path, class:"btn"
        %li
          = link_to "ポイントに関する特約",root_path, class:"btn"
    %li.content
      %h2.content__head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧",root_path, class:"btn"
        %li
          = link_to "ブランド一覧",root_path, class:"btn"
    %li.content
      %h2.content__head ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド",root_path, class:"btn"
        %li
          = link_to "FURIMAロゴ利用ガイドライン",root_path, class:"btn"
        %li
          = link_to "お知らせ",root_path, class:"btn"
  .footer__logo
    = link_to root_path do
      = image_tag asset_path("logo-white.png"), alt: "logo-white.png"
  %p © FURIMA

.seller-content
  - if user_signed_in?
    = link_to new_item_path do
      .exhibition-btn
        %span.exhibition-btn__text 出品する
        = image_tag "icon_camera.png", class: "exhibition-btn__icon"
  - else
    = link_to new_user_session_path do
      .exhibition-btn
        %span.exhibition-btn__text 出品する
        = image_tag "icon_camera.png", class: "exhibition-btn__icon"

app/views/items/_main-header.html.haml
.pcheader__inner
  .pcheader__inner__mainheader
    .pcheader__inner__mainheader__furimalogo
      = link_to root_path do
        = image_tag asset_path("logo.png"), alt: "FURIMA"
    .searchBox
      = search_form_for @q, url:search_items_path, class: "searchBox" do |form|
        = form.search_field :name_cont, placeholder: "キーワードから探す", class: "#searchInput.searchBox--input" 
        .searchBox__icon
          = button_tag type: 'submit', class: 'search-btn' do
            = image_tag asset_path("icon-search 1.png"), alt: "icon-search 1.png エラー" 
  .nav
    %ul.nav__listsleft
      %li
        = link_to "カテゴリー"
      %li.listsleft__item
        = link_to "ブランド"
    - if user_signed_in?
      %ul.nav__listsright
        %li.listsRight__item
          = link_to "マイページ", user_path(current_user.id)
    - else
      %ul.nav__listsright
        %li.listsRight__item
          = link_to "ログイン",new_user_session_path
        %li.listsRight__item
          = link_to "新規会員登録",new_user_registration_path

app/views/items/create.html.haml
-# 商品出品完了ページ
.products-done__body
  = render "header"
  .products-done__main
    %h2 出品が完了しました
    .products-done__main__explanation
      %h1 あなたが出品した商品は
      =link_to "「出品した商品一覧」",root_path, class:"btn"
      からいつでも見ることが出来ます。
    .products-done__main__choice
      .exhibition
        = link_to "続けて出品する",new_item_path, class:"btn"
      .return
        = link_to "トップページへ戻る",root_path, class:"btn"
  = render "footer"

app/views/items/destory.html.haml
-# 商品削除完了画面
.delete-done
  .delete-done__header
    .delete-done__header__logo
      = link_to image_tag('logo.png', class: "btn"),root_path
  .delete-done__main
    %h2 商品の削除されました
    .delete-done__main__explanation
      %h1 あなたが出品した商品は
      =link_to "「出品した商品一覧」",root_path, class:"btn"
      からいつでも見ることが出来ます。
    .delete-done__main__choice
      .return
        = link_to "トップページへ戻る",root_path, class:"btn"
  .delete-done__footer
    %ul
      %li
        = link_to 'プライバシーポリシー', "#", class: "footer-text"
      %li
        = link_to 'FURIMA利用規約', "#", class: "footer-text"
      %li
        = link_to '特定商取引に関する表記', "#", class: "footer-text"
    .delete-done__footer__logo
      = link_to image_tag('logo.png', class: "delete-done__footer__logo__icon"),root_path
      %p © FURIMA

app/views/items/done.html.haml
-# 商品購入完了画面
.purchase-verification
  = render "header"
  .purchase-done__main
    .purchase-done__main__up
      %h2 発送をお待ちください
      %h3 出品者からの発送通知をお待ち下さい
    .purchase-done__main__explanation
      %h1 購入が完了しました
    .purchase-done__main__box
      .product 
        .photo
          = image_tag @item.images[0].src.url, size: '200x200'
    .name
      = "商品名 #{@item.name}"
    .detail
      .money
        ="送料込み ¥#{@item.price}"
    .purchase-done__main__delivery
      .address
        %ul.address--delivery
          配送先
        %li=@item.user.address.postal_code
        %li="#{current_user.address.prefecture_code} #{current_user.address.city_name} #{current_user.address.street}#{current_user.address.street2}"
        %li="購入者 #{current_user.first_name} #{current_user.last_name} " 
    .purchase-done__main__payment
      .method
        %ul.method--number
          支払方法
          %li
            = "**** **** **** " + @default_card_information.last4
          %li
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
    .purchase-done__main__return
      .purchase-done__main__return__box
        =link_to 'TOPページへ戻る',root_path, class:"return_btn"
  = render "footer"

app/views/items/edit.html.haml
.single-container
  = render "header"
  %main.single-main
  %section.l-single-container.buy-item-container
    #sell-container
      .sell-container-inner
        %h2.l-single-head
          商品の情報を入力
        - if flash[:alert]
          %p.alert
            = flash[:alert]
        = form_with model: @item,local: true, class: "sell-form" do |f|
          .sell-upload-box
            %h3.sell-upload-head
              出店画像
              %span.form-require 必須
            %p 最大5枚までアップロードできます
            #image-box
              #previews
                - if @item.persisted?
                  - @item.images.each_with_index do |image, i|
                    = image_tag image.src.url, data: { index: i } ,class: 'input-image'
              = f.fields_for :images do |image|
                .js-file_group{"data-index": "#{image.index}"}
                  = image.file_field :src, class: "js-file" #sell-upload-drop-file
                  %br/
                  %span.js-remove 削除
                - if @item.persisted?
                  = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
              - if @item.persisted?
                .js-file_group{"data-index" => "#{@item.images.count}"}
                  = file_field_tag :src, name: "item[images_attributes][#{@item.images.count}][src]", class: 'js-file'
                  .js-remove 削除
          .sell-content
            .form-group
              %label
                商品名
                %span.form-require 必須
              %div
                = f.text_field :name, placeholder: "商品名 (必須 40文字まで)", class: "input-default"
            .form-group
              %label
                商品の説明
                %span.form-require 必須
              = f.text_area :content, placeholder: "商品の説明 (必須1000文字以内) (色、素材、重さ、定価、注意点など) 例)1900年頃のヴィンテージアウターです。ブラックで少し汚れがあります。あなたのハートを射止めます！", rows: "5", class: "textarea-default"
          .sell-content.clearfix
            %h3.sell-sub-head 商品の詳細
            .sell-form-box
              .form-group.category
                %label
                カテゴリー
                %span.form-require 必須
                .select-wrap
                  - @parents.each do |parent|
                    - if @item.category_id == parent.id
                      .select-wrap__box.parent
                        = f.collection_select(:category_id, Category.where(ancestry: nil), :id, :name, {prompt: "選択して下さい", selected: parent.parent.parent.id}, {id: "parent"})
                      .child-edit
                        = f.collection_select(:category_id, Category.where(params[:category_id]), :id, :name, {prompt: "選択して下さい", selected: parent.parent.id}, {id: "child"})
                      .grand_child-edit
                        = f.collection_select(:category_id, Category.where(params[:category_id]), :id, :name, {prompt: "選択して下さい", selected: parent.id}, {id: "grand_child"})
              .form-group
                %label
                  サイズ
                  %span.form-require 必須 
                %div
                  .select-wrap
                    = f.collection_select(:size_id, Size.where(params[:size_id]), :id, :value, {prompt: "選択して下さい", selected: @item.id}, class: "select-default")
              .form-group
                %label
                  ブランド
                  %span.form-require-sub 任意
                %div
                  .select-wrap
                    = f.text_field :brand, placeholder: "例)シャネル", class: "select-default" 
              .form-group
                %label
                  商品の状態
                  %span.form-require 必須 
                %div
                  .select-wrap
                    = f.collection_select(:condition_id, Condition.where(params[:condition_id]), :id, :value, {prompt: "選択して下さい", selected: @item.id}, class: "select-default")
          .sell-content.clearfix
            %h3.sell-sub-head 配送について
            = link_to "?", "#", target: "_blank", class: "form-question"
            .sell-form-box
              .form-group.burden
                %label
                  配送料の負担
                  %span.form-require 必須
                %div
                  .select-wrap
                    = f.collection_select(:delivery_fee_id, DeliveryFee.where(params[:delivery_fee_id]), :id, :value, {prompt: "選択して下さい", selected: @item.id}, class: "select-default")
              .form-group
                %label
                  配送方法
                  %span.form-require 必須
                %div
                  .select-wrap
                    = f.collection_select(:delivery_way_id, DeliveryWay.where(params[:delivery_way_id]), :id, :value, {prompt: "選択して下さい", selected: @item.id}, class: "select-default")
              .form-group
                %label
                  発送元の地域
                  %span.form-require 必須
                %div
                  .select-wrap                                                    
                    = f.collection_select(:prefecture_id, Prefecture.where(params[:prefecture_id]), :id, :name, {prompt: "選択して下さい", selected: @item.id}, class: "select-default")
              .form-group
                %label
                  発送までの日数
                  %span.form-require 必須
                %div
                  .select-wrap
                    = f.collection_select(:delivery_date_id, DeliveryDate.where(params[:delivery_date_id,]), :id, :value, {prompt: "選択して下さい", selected: @item.id}, class: "select-default")
          .sell-content.clearfix
            %h3.sell-sub-head 販売価格(300~9,999,999)
            = link_to "?", "#", target: "_blank", class: "form-question"
            .sell-form-box
              %ul.sell-price
                %li.form-group
                  .clearfix
                    %label.l-left
                      価格
                      %span.form-require 必須
                    .l-right.sell-price-input
                      %div
                        = f.text_field :price, placeholder: "例)300", class: "input-default price",id: "sell-price"
                %li.clearfix
                  .l-left 販売手数料(10%)
                  .l-right#comercial_cost --
                %li.clearfix.bold
                  .l-left 販売利益
                  .l-right#profit --
          .modal{role: "dialog", tabindex: "-1"}
            .modal-inner
          .sell-content.sell-btn-box
            %div
              %p
                = link_to "禁止されている出品", "#"
                、
                = link_to "行為", "#"
                を必ずご確認ください。
              %p
                またブランド品でシリアルナンバー等がある場合はご記載ください。
                = link_to "偽ブランドの販売",  "#"
                は犯罪であり処罰される可能性があります。
              %p
                また、出品にもちまして
                = link_to "加盟店規約", "#"
                に同意したことになります。
            = f.submit "再出品する", class: "btn-default btn-red"
            = link_to "もどる", root_path, class: "btn-default btn-gray"
          .overlay
  = render "footer"

app/views/items/purchase.html.haml
-# 商品購入確認画面
.purchase-verification
  = render "header"
  .purchase-verification__main
    .purchase-verification__main__up
      購入内容の確認
    .purchase-verification__main__box
      .product 
        .photo
          = image_tag @item.images[0].src.url, size: '200x200'
        .name
          = "商品名 #{@item.name}"
      %ul.detail
        %li.money="送料込み ¥#{@item.price}"
    .purchase-verification__main__pay
      .purchase-verification__main__pay__point
        ポイントはありません
      .purchase-verification__main__pay__money
        .purchase-verification__main__pay__money--left
          支払金額
        .purchase-verification__main__pay__money--right
          =" ¥#{@item.price}"
      .purchase-verification__main__pay__decision
        - if @default_card_information.blank?
          .buy-btn 
            支払い方法を追加してください。
        - else
          = form_tag(action: :pay, method: :post) do
            %button.buy-btn 購入する
    .purchase-verification__main__delivery
      .address
        %ul.address--delivery
          配送先
        %li=@item.user.address.postal_code
        %li="#{current_user.address.prefecture_code} #{current_user.address.city_name} #{current_user.address.street}#{current_user.address.street2}"
        %li="購入者 #{current_user.first_name} #{current_user.last_name} " 
        .address--change
          = link_to address_user_path(current_user.id), class:"address--change--btn" do
            変更する
    .purchase-verification__main__payment
      .method
        %ul.method--number
          支払方法
        - if @default_card_information.blank?
          .method--change
            = link_to "クレジットカードを登録する",confirmation_card_path(current_user.id),class: "method--change--btn"
        - else
          %li
            = "**** **** **** " + @default_card_information.last4
          %li
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          .method--change
            = link_to confirmation_card_path(current_user.id), class:"method--change--btn" do
              変更する
  = render "footer"

app/views/items/show.html.haml
-# 下記はメインヘッダー呼び出しに使用している
= render "items/main-header"
.product-main
  .product-main__show
    .top-content
      .products-box
        %h2.products-box__name
          = @item.name
        .products-box__images
          %ul.top-list
            %li.top-image
              - @item.images.first(1).each do |item|
                = image_tag item.src.url, class: 'top-icon'
            %ul.sub-images
              - @item.images[0..4].each do |item|
                %li.sub-images--box
                  = image_tag item.src.url, class: 'sub-icon' 
        .products-box__price
          .products-box__price__texts
            .price-text ¥
            .price-text
              = @item.price
          .products-box__price__detail
            %span (税込)
            %span 送料込み
        .products-box__detail
          = @item.content
        .products-box__info
          %table
            %tbody
              %tr
                %th 出品者
                %td
                  = @item.user.nickname
              %tr
                %th カテゴリー
                %td.category-text
                  - @parents.each do |parent|
                    - if @item.category_id == parent.id
                      = link_to "#" do
                        = parent.parent.parent.name
                        %br
                      = link_to "#" do
                        = parent.parent.name
                        %br
                      = link_to "#" do
                        = parent.name
                     


              %tr
                %th ブランド
                %td
                  = @item.brand
              %tr
                %th 商品のサイズ
                %td
                  = @item.size.value
              %tr
                %th 商品の状態
                %td
                  = @item.condition.value
              %tr
                %th 配送料の負担
                %td
                  = @item.delivery_fee.value
              %tr
                %th 発送元の地域
                %td
                  = link_to "#" do
                    = @item.prefecture.name
              %tr
                %th 発送日の目安
                %td
                  = @item.delivery_date.value
        .products-box__option
          .favorite
            = render 'likes/like_links', item: @item
          .optional
            .optional__btn
              = link_to "#", class: "optional__btn__link" do
                = icon('fas', 'flag', class: 'image-icon') 
                不適切な商品の通報
                
        .comments-box
          .message-box
            -if @comments 
              -@comments.each do |comment|
                .comments-box__message
                  .comments-box__message__items
                    .comments-box__message__items__user
                      .comments-box__message__items__user__name
                        = comment.user.nickname
                    .comments-box__message__items__body
                      = comment.text
                      .comments-box__message__items__body__icons
                        .comments-box__message__items__body__icons__left
                          = icon('fas', 'history')
                          %span
                            = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
                        .comments-box__message__items__body__icons__right
                          .message-delete
                            = link_to "/items/#{@item.id}/comments/#{comment.id}", method:"delete", id: :delete_btn do
                              = icon('fas', 'trash')

          -if current_user
            .caution-area
              %p
                相手のことを考え丁寧なコメントを心がけましょう。
              %p
                不快な言葉遣いなどは利用制限や退会処分となることがあります。
            = form_for [@item, @comment], html: { id: :new_comment } do |f|
              = f.text_area :text, placeholder: "コメントして下さい",class: "comment-area"
              .comment-btn
                = f.submit "コメントする", class: "comment-btn__submit"

        - if user_signed_in? && current_user.id == @item.user_id   
          .edit-btn
            = link_to "編集", edit_item_path(@item.id), class:"edit-btn__text"
          .delete-btn
            = link_to '削除する', item_path, method: :delete, class:"delete-btn__text"
        - elsif user_signed_in?
          -if @item.buyer_id.present?
            .purchase-btn-red
              .purchase-btn-red__text
                Sold out 
          - else
            .purchase-btn
              = link_to "購入する", purchase_items_path, class:"purchase-btn__text"
      .product-links
        .product-links__before
          = link_to "#", class: "product-link-btn" do
            = icon('fas', 'angle-left', class: 'image-icon')
            %span 前の商品
        .product-links__after
          = link_to "#", class: "product-link-btn" do
            %span 後ろの商品
            = icon('fas', 'angle-right', class: 'image-icon')
      .see-more
        = link_to  'メンズをもっと見る', "#"
  = render "items/main-footer"
-# 上記はメインフッター呼び出しに使用している